extends Node2D

var dialogue_sequence = ["There's something sinister about it.",
"It stares into the distance, ignoring your presence.",
"You step try to get close, it twitches, never losing its gaze on the horizon.",
"You hear small buzzes and mechanical clicks from within its body, a constant drone of electricity.",
"It seems frozen in time...",
"Something's wrong...",
"The air around it feels heavy.",
"As you approach, a low hum resonates from within its cold body.",
"Its eyes reflect an unnatural glow, you don't want to be here.",
"The silence is broken by the occasional mechanical whir, startling you.",
"You catch glimpses of faint archaic symbols occasionally flashing on its screen. You can't make them out.",
"It remains still, indifferent to the world and its surroundings.",
"A faint static fills the air, echoing an uneasy ambience through the cracks of your mind.",
"As much as you want to get closer, you can't bring yourself to do so.",
"Its gaze holds the weight of forgotten memories and a past long gone. You ponder who and what it is.",
"The flickering lights from within its body cast eerie shadows upon the ground.",
"The air grows colder the longer you stay.",
"You think you can hear occasional whispers echoing through its body."]
